config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
  omniauth_callbacks: "users/omniauth_callbacks" }

  resources :users, only: %i[show edit update] do
    get "point" => "users#total_point"
    post "add_point" => "users#add_point"
    post "subtract_point" => "users#subtract_point"

    resources :rewards, only: %i[new create index] do
    post "update_completed" => "rewards#update_completed"
    end
  end

  get "others/getting_ready" => "others#getting_ready"
  get "others/point_explanation" => "others#point_explanation"

  resources :notifications, only: :index

  get "recipes/look" => "recipes#look"
  get "recipes/ranking" => "recipes#ranking"

  resources :recipes, only: %i[index new create show edit update destroy] do
    collection do
      get :favorites
    end
    get :search, on: :collection
    resources :comments, only: %i[create edit update destroy], shallow: true
  end
  resources :favorites, only: %i[create destroy]

  root "others#top"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
    validates :content, presence: true, length: { maximum: 65_535 }

    belongs_to :user
    belongs_to :recipe
    has_many :notifications, dependent: :destroy
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = current_user.comments.build(comment_params)
    @comment.save
    @recipe = @comment.recipe
    @recipe.create_notification_comment!(current_user, @comment.id)
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment.destroy!
  end

  def edit
    @comment = Comment.find(params[:id])
    @recipe = @comment.recipe
  end

  def update
    @comment = Comment.find(params[:id])
    @recipe = @comment.recipe
    if @comment.update(comment_edit_params)
      # 更新成功時の処理
    else
      # 更新失敗時の処理
      puts @comment.errors.full_messages
    end
  end

    private

  def comment_params
    params.require(:comment).permit(:content).merge(recipe_id: params[:recipe_id])
  end

  def comment_edit_params
    params.require(:comment).permit(:content)
  end
end

app/views/comments/_comment.html.erb
<%= turbo_frame_tag comment do %>
  <div id="comment-<%= comment.id %>">
    <div class="border-b border-gray-400 p-2 mb-2 md:mb-6">
      <div>
        <div class="flex justify-between text-[10px] sm:text-[15px]">
          <h3>○<%= comment.user.name %></h3>
          <%= comment.created_at.strftime("%Y年%m月%d日") %>
        </div>
        <div class="flex justify-between items-end">
          <div class="p-2">
            <p class="text-[12px] sm:text-[18px]"><%= simple_format(comment.content) %></p>
          </div>
          <div class="text-[12px] sm:text-[16px]">
            <% if current_user && current_user.own?(comment) %>
              <%= link_to "削除", comment_path(comment), data: { turbo_method: :delete, turbo_confirm: "コメントを削除します。" }, class: "delete-comment-link rounded-lg  bg-red-500 text-white px-4 mr-2" %>
              <%= link_to "編集", edit_comment_path(comment), data: { turbo: true }, class: "edit-comment-link rounded-lg bg-green-400 text-stone-700 px-4" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/comments/_form.html.erb
<div class="row mb-3 md:flex md:justify-center" id="comment-form">
  <%= form_with model: comment, url: recipe_comments_path(recipe) do |f| %>
    <div>
      <%= f.label :content, "コメントを送ろう！", class: "text-[14px] sm:text-[20px] font-bold p-2" %></br>
      <%= f.text_area :content, class: "bg-gray-300 w-full md:w-230 p-2 mt-5",row: "3", placeholder: "コメント" %></br>
      <div class="text-center">
        <% if current_user %>
          <%= f.submit "投稿", class: "btn btn-primary text-[12px] sm:text-[18px] rounded-lg border px-4 py-1 my-3", style: "background-color: #F2EDED;" %>
        <% else %>
          <%= f.submit "投稿", class: "btn btn-primary text-[12px] sm:text-[18px] rounded-lg border px-4 py-1 my-3", style: "background-color: #F2EDED;", onclick: "alert('コメントするにはログインが必要です。'); return false;" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/comments/create.turbo_stream.erb
<% if @comment.errors.present? %>
  <%= turbo_stream.replace "comment-form" do %>
    <%= render 'comments/form', comment: @comment, recipe: @comment.recipe %>
  <% end %>
<% else %>
  <%= turbo_stream.prepend "table-comment" do %>
    <%= render 'comments/comment', comment: @comment %>
  <% end %>
  <%= turbo_stream.replace "comment-form" do %>
    <%= render 'comments/form', comment: Comment.new, recipe: @comment.recipe %>
  <% end %>
<% end %>

app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.remove "comment-#{@comment.id}"  %>

app/views/comments/edit.html.erb
<%= turbo_frame_tag @comment do %>
    <div class="border-b row mb-3 md:flex md:justify-center" id="comment-edit-form">
      <%= form_with model: @comment, url: comment_path(@comment) do |f| %>
        <div class="rounded-lg bg-gray-200 px-3 md:px-5 ">
          <%= f.label :" " %></br>
          <%= f.text_area :content, class: "bg-amber-50 border w-full md:w-230 p-2", placeholder: "コメント" %></br>
          <div class="text-right text-[10px] sm:text-[16px]">
            <%= link_to "キャンセル", recipe_path(@recipe), class: "btn btn-primary rounded-lg border px-4 py-1 my-3", style: "background-color: #F2EDED;", data: { remote: true } %>
            <%= f.submit "保存", class: "btn rounded-lg border px-4 py-1 my-3", style: "background-color: #F2EDED;" %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>

app/views/comments/update.turbo_stream.erb
<%= turbo_stream.replace "comment-edit-form" do %>
  <%= render 'comment', comment: @comment, recipe: @recipe  %>
<% end %>