config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
  omniauth_callbacks: "users/omniauth_callbacks" }

  resources :users, only: %i[show edit update] do
    get "point" => "users#total_point"
    post "add_point" => "users#add_point"
    post "subtract_point" => "users#subtract_point"

    resources :rewards, only: %i[new create index] do
    post "update_completed" => "rewards#update_completed"
    end
  end

  get "others/getting_ready" => "others#getting_ready"
  get "others/point_explanation" => "others#point_explanation"

  resources :notifications, only: :index

  get "recipes/look" => "recipes#look"
  get "recipes/ranking" => "recipes#ranking"

  resources :recipes, only: %i[index new create show edit update destroy] do
    collection do
      get :favorites
    end
    get :search, on: :collection
    resources :comments, only: %i[create edit update destroy], shallow: true
  end
  resources :favorites, only: %i[create destroy]

  root "others#top"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  mount_uploader :image,  RecipeImageUploader

  belongs_to :user

  validates :title, presence: true
  validates :get_point, presence: true

  has_many :ingredients,  dependent: :destroy
  accepts_nested_attributes_for :ingredients, allow_destroy: true,  reject_if: lambda { |attributes| attributes["name"].blank? }
  has_many :instructions,  dependent: :destroy
  accepts_nested_attributes_for :instructions, allow_destroy: true,  reject_if: lambda { |attributes| attributes["content"].blank? }

  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :recipe_tags, dependent: :destroy
  has_many :tags, through: :recipe_tags

  has_many :notifications, dependent: :destroy

  scope :with_tag, ->(tag_id) { joins(:recipe_tags).where(recipe_tags: { tag_id: tag_id }) }
  def self.ransackable_attributes(auth_object = nil)
    %w[title] # 検索可能な属性を指定
  end

  def create_notification_favorite!(current_user)
    # すでに「いいね」されているか検索
    temp = Notification.where([ "visitor_id = ? and visited_id = ? and recipe_id = ? and action = ? ",  current_user.id, user_id, id, "favorite" ])
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        recipe_id: id,
        visited_id: user_id,
        action: "favorite"
      )
      # 自分の投稿に対するいいねの場合は、通知済みとする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  def create_notification_comment!(current_user, comment_id)
    notification = current_user.active_notifications.new(
      recipe_id: id,
      comment_id: comment_id,
      visited_id: user_id,
      action: "comment"
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[edit update destroy ]
  before_action :authenticate_user!, only: [ :new, :create ]

  # GET /recipes or /recipes.json
  def index
    @q = Recipe.ransack(params[:q])
      if params[:tag_id].present?
        @recipes = Recipe.with_tag(params[:tag_id]).page(params[:page]).per(9)
      else
        @recipes = @q.result.page(params[:page]).per(9)
      end
    @tags = Tag.all
  end

  def look
    @tags = Tag.all
    @q = Recipe.ransack(params[:q])
  end

  def search
    @recipes = Recipe.where("title like ?", "%#{params[:q]}%")
    render partial: "recipes/search", locals: { recipes: @recipes }
  end

  def ranking
    @recipe_ranks = Recipe.find(Favorite.group(:recipe_id).order("count(recipe_id) desc").limit(6).pluck(:recipe_id))
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])
    @comment = Comment.new
    @comments = @recipe.comments.includes(:user).order(created_at: :desc)
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
    @recipe.ingredients.build
    @recipe.instructions.build
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = current_user.recipes.build(recipe_params)
    @recipe.remote_image_url = retouch_image(params[:recipe][:image])

    respond_to do |format|
      if @recipe.save
        if params[:recipe][:tag_id].present?
          RecipeTag.create(recipe_id: @recipe.id, tag_id: params[:recipe][:tag_id])
        end
        format.html { redirect_to @recipe, notice: "レシピを作成しました。" }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        @recipe.recipe_tags.destroy_all
        if params[:recipe][:tag_id].present?
          RecipeTag.create(recipe_id: @recipe.id, tag_id: params[:recipe][:tag_id])
        end

        format.html { redirect_to @recipe, notice: "レシピの更新に成功しました。" }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy!

    respond_to do |format|
      format.html { redirect_to recipes_path, status: :see_other, notice: "レシピの削除に成功しました。" }
      format.json { head :no_content }
    end
  end

  def favorites
    if  params[:tag_id].present?
      @favorite_recipes = current_user.favorite_recipes.includes(:user).with_tag(params[:tag_id]).order(created_at: :desc).page(params[:page]).per(9)
    else
      @favorite_recipes = current_user.favorite_recipes.includes(:user).order(created_at: :desc).page(params[:page]).per(9)
    end
    @tags = Tag.all
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = current_user.recipes.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recipe_params
      params.require(:recipe).permit(:title, :trick, :get_point, :image, :image_cache, tag_id: [], ingredients_attributes: [ :id, :name, :quantity, :_destroy ], instructions_attributes: [ :id, :step, :content, :_destroy ])
    end

    def retouch_image(image)
      if image.blank?
        uploaded_image = Cloudinary::Uploader.upload(Rails.root.join("app/assets/images/no_image.png"),
        transformation: [ { width: 250, height: 300, crop: "fit", background: "white" } ])
      else
        uploaded_image = Cloudinary::Uploader.upload(image.tempfile.path,
        transformation: [ { width: 250, height: 300, crop: "fit", background: "white" } ])
      end
      uploaded_image["url"]
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_favorite.html.erb
<%= link_to favorites_path(recipe_id: recipe.id), id: "favorite-button-for-recipe-#{recipe.id}", data: { turbo_method: :post } do %>
  <div class="no_favorite flex">  
    <svg class="h-6 w-6 sm:h-8 sm:w-8 text-red-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"/>
    </svg>
    <div class="mt-2 text-[12px] md:text-[15px]">
      <%= recipe.favorites.count %>
    </div>
  </div>
<% end %>

app/views/recipes/_favorite_buttons.html.erb
<div class="heart_botton">
  <% if current_user %>
    <% if current_user.favorite?(recipe) %>
      <%= render 'unfavorite', { recipe: recipe } %>
    <% else %>
      <%= render 'favorite', { recipe: recipe } %>
    <% end %>
  <% else %>
    <%= link_to favorites_path(recipe_id: recipe.id), id: "favorite-button-for-recipe-#{recipe.id}", data: { turbo_method: :post }, onclick: "alert('いいねにはログインが必要です。'); return false;" do %>
      <div class="no_favorite flex">  
        <svg class="h-6 w-6 sm:h-8 sm:w-8 text-red-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"/>
        </svg>
        <div class="mt-2 text-[12px] md:text-[15px]">
          <%= recipe.favorites.count %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/recipes/_form.html.erb
<%= form_with model: @recipe do |f| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex sm:ml-200 whitespace-nowrap">
    <div class="pt-2">
      <%= link_to "レシピ一覧へ", recipes_path, onclick: "if (confirm('内容を破棄して戻ります')) { window.location.href = '#{recipes_path}'; } return false;" %>
    </div>
    <% if @recipe && @recipe.id %>
      <%= link_to "リセット", edit_recipe_path(@recipe.id), class: "rounded-lg bg-red-500 text-white px-4 my-2 ml-6", onclick: "if (confirm('入力内容をリセットします')) { window.location.href = '#{edit_recipe_path(@recipe.id)}'; } return false;" %>
    <% else %>
      <%= link_to "リセット", new_recipe_path, class: "rounded-lg bg-red-500 text-white px-4 my-2 ml-6", onclick: "if (confirm('入力内容をリセットします')) { window.location.href = '#{new_recipe_path}'; } return false;" %>
    <% end %>
    <%= f.submit "投稿", class: "rounded-lg bg-green-400 text-stone-700 px-4 my-2 ml-2" %>
  </div>

  <div class="md:flex">
    <div class="text-[15px] py-2">
      <%= f.label :"", style: "display: block;", for: 'image_input' %>
      <%= f.file_field :image, id: 'image_input', style: "display: none;" %>
      <%= f.hidden_field :image_cache %>
      <label for="image_input" class="bg-gray-200 text-center cursor-pointer inline-block w-full sm:w-[400px] sm:h-[25px] flex items-center justify-center">
        料理の写真をのせる
      </label>
      <img id="image_preview" src="<%= @recipe.image.url %>" alt="Image Preview" class="w-full sm:w-[400px]" style="display: block;" />
    </div>
    <div class="py-2 md:ml-30">
      <%= f.label :"【レシピ名】", style: "display: block;", class:"text-[16px] sm:text-[20px]" %>
      <%= f.text_field :title, required: true, style: "text-align: center;", placeholder: " 例）カレーライス", class: "title text-[25px] w-full sm:text-[30px] sm:w-135 sm:h-15 mb-4 bg-gray-300" %></br>
      <%= f.label :tag_id, "【ターゲットの食材】", class: "block  sm:mt-10 text-[16px] sm:text-[20px]" %>
      <% if @recipe.tags.present? %>
        <%= f.collection_select :tag_id, Tag.all, :id, :name, { selected: @recipe.tags.pluck(:id) }, class: "tag text-[20px] w-full sm:text-[30px] sm:w-135 sm:h-15 mb-3 sm:mb-8 bg-gray-300 text-gray-500", style: "text-align: center;" %>
      <% else %>
        <%= f.collection_select :tag_id, Tag.all, :id, :name, { include_blank: "食材を選択" }, class: "tag text-[20px] w-full sm:text-[30px] sm:w-135 sm:h-15 mb-3 sm:mb-8 bg-gray-300 text-gray-500", style: "text-align: center;" %>
      <% end %>
      <div class="flex items-center text-[12px] sm:text-[16px] py-2">
        <%= f.label :"克服ポイント：", style: "margin-right: 10px;"%>
        <%= f.number_field :get_point, in: 1..3, step: 1, required: true, style: "text-align: center;" , class: "w-6 sm:w-12 h-6 sm:h-6 point bg-gray-300" %>
      </div>
      <p class="mt-1 md:mt-4 text-red-700 text-[14px] sm:text-[16px]">※ポイントはターゲットの食材の食べやすさに応じ、1~3の数値を入力してください</p>
    </div>
  </div>
  <div class="md:flex">
    <div class="mt-5 w-90">
      <div id="ingredients">
        <div class="text-[16px] sm:text-[20px] mb-3 md:mb-5">
         【材料】
        </div>
        <%= f.fields_for :ingredients do |ingredient_fields| %>
          <div class="ingredient flex items-center mb-3">
            <%= ingredient_fields.hidden_field :_destroy %>
            <%= ingredient_fields.text_field :name, placeholder: " 例）にんじん", class: "bg-gray-300 p-1 w-60" %>
            <%= ingredient_fields.text_field :quantity, placeholder: "例）1本", class: "bg-gray-300 ml-5 p-1 w-18" %>
            <input type="button" value="削除" class="ml-2" onclick="deleteRow(this)">
          </div>
        <% end %>
      </div>
      <button id="add-ingredient" type="button">＋材料を追加</button>
    </div>
    <div class="mt-5 md:ml-50">
      <div class="text-[16px] sm:text-[20px] mb-3 md:mb-5">
      【手順】
      </div>
      <div id="instructions" class="grid grid-cols-1 lg:grid-cols-2 xl:grid-cols-3 gap-4 md:gap-7">
        <%= f.fields_for :instructions do |instruction_fields| %>
          <div class="instructions flex flex-col">
            <%= instruction_fields.hidden_field :_destroy %>
            <%= instruction_fields.text_field :step, placeholder: "例)1", class: "bg-gray-300 w-10 mb-1 p-1 text-lg font-semibold" %>
            <%= instruction_fields.text_area :content, placeholder: "例）野菜を切り、飴色になるまでよく炒める。焦がさないように注意。", 
                class: "bg-gray-300 w-55 h-30 mb-2 px-2 brock" %>
            <input type="button" value="削除" onclick="deleteRow(this)" class="underline mb-2 text-left ml-45 md:ml-0">
          </div>
        <% end %>
      </div>
      <div class="md:ml-55 w-30">
        <button id="add-instruction" type="button">＋手順を追加</button>
      </div>
    </div>
  </div>
  <div class="md:ml-160 mt-5 md:mt-10 pb-5 ">
    <p class="text-[16px] md:text-[20px] mb-3 md:mb-5 md:w-40">【コツ・工夫点】</p>
    <%= f.label :" ", style: "display: block" %>
    <%= f.text_area :trick, style: "font-size: 14px; height: 60px; text-align: start; word-wrap: break-word;", placeholder: " 例）野菜がしんなりするまでよく炒める。歯応えが少なくなり食べやすくなります。", class: "w-full md:w-125 h-48 bg-gray-300 p-1" %>
  </div>
<% end %>


<script>
  document.getElementById('image_input').addEventListener('change', function(event) {
        const file = event.target.files[0];
        const reader = new FileReader();
        
        reader.onload = function(e) {
            const img = document.getElementById('image_preview');
            img.src = e.target.result; // 選択した画像のURLを設定
            img.style.display = 'block'; // 画像を表示
        }
        
        if (file) {
            reader.readAsDataURL(file); // 選択したファイルを読み込む
        }
    });
  document.getElementById('add-ingredient').addEventListener('click', function() {
    const ingredientsDiv = document.getElementById('ingredients');
    const newIndex = ingredientsDiv.children.length; // 現在の行数を取得

    const newIngredientDiv = document.createElement('div');
    newIngredientDiv.className = 'ingredient flex items-center mb-3'; // フレックスボックスを追加
  
    newIngredientDiv.innerHTML = `
      <input type="hidden" name="ingredient[_destroy]" value="0"> 
      <input type="text" name="recipe[ingredients_attributes][${newIndex}][name]" placeholder=" 例）にんじん" class="bg-gray-300 p-1 w-60">
      <input type="text" name="recipe[ingredients_attributes][${newIndex}][quantity]" placeholder="例）1本" class="bg-gray-300 ml-5 p-1 w-18">
      <input type="button" value="削除" class="ml-2" onclick="deleteRow(this)">
    `;

    ingredientsDiv.appendChild(newIngredientDiv);
  });
  function deleteRow(button) {
    const ingredientDiv = button.parentElement;
    const hiddenField = ingredientDiv.querySelector('input[type="hidden"]');
    hiddenField.value = '1'; // _destroyを1に設定
    ingredientDiv.style.display = 'none'; // フォームを非表示にする
  }
  document.getElementById('add-instruction').addEventListener('click', function() {
    const instructionsDiv = document.getElementById('instructions');
    const newIndex = instructionsDiv.children.length; // 現在の行数を取得

    const newInstructionDiv = document.createElement('div');
    newInstructionDiv.className = 'instruction flex flex-col';
  
    newInstructionDiv.innerHTML = `
      <input type="hidden" name="instruction[_destroy]" value="0"> 
      <input type="text" name="recipe[instructions_attributes][${newIndex}][step]" placeholder="例)1" class="bg-gray-300 w-10 mb-1 p-1 text-lg brock font-semibold">
      <textarea name="recipe[instructions_attributes][${newIndex}][content]" placeholder="例）野菜を切り、飴色になるまでよく炒める。焦がさないように注意。" class="bg-gray-300 mb-2 w-55 h-30 px-2 brock"></textarea>
      <input type="button" value="削除" onclick="deleteRow(this)" class="underline mb-2 text-left ml-45 md:ml-0">
    `;

    instructionsDiv.appendChild(newInstructionDiv);
  });
  function deleteRow(button) {
    const instructionDiv = button.parentElement;
    const hiddenField = instructionDiv.querySelector('input[type="hidden"]');
    hiddenField.value = '1'; // _destroyを1に設定
    instructionDiv.style.display = 'none'; // フォームを非表示にする
  }
</script>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
  <div class="flex sm:w-60 flex-wrap justify-center rounded-lg border border-amber-50 shadow-lg my-2 bg-white">
    <div class="m-4 sm:m-6">
      <%= link_to(recipe)  do %>
        <dev class="flex justify-center">
          <%= cl_image_tag(recipe.image.url(:index_size)) %>
        </dev>
        <div class="text-[20px] font-bold text-center">
          <%= "#{recipe.title}" %>
        </div>
        <div class="flex justify-between w-50">
          <div class="flex">
            <%= render 'favorite_buttons', recipe:recipe %>
          </div>
          <div class="text-[16px] mt-1 mr-3">
            <p><%= "克服ポイント：""#{recipe.get_point}" %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/_search.html.erb
<div class="border border-neutral-500">
  <% @recipes.uniq(&:title).each do |recipe| %>
    <li class="w-full md:w-130 flex items-center bg-white border-t gap-x-3.5 py-1 md:py-2 px-2 md:px-3 text-sm text-gray-800 hover:bg-blue-200 focus:ring-2 focus:ring-blue-500 dark:text-gray-400 dark:hover:bg-blue-200 dark:hover:text-gray-300" role="option" data-autocomplete-value="<%= recipe.id %>" data-autocomplete-label="<%= recipe.title %>">
      <%= recipe.title %>
    </li>
  <% end %>
</div>

app/views/recipes/_unfavorite.html.erb
<%= link_to favorite_path(current_user.favorites.find_by(recipe_id: recipe.id)), id: "unfavorite-button-for-recipe-#{recipe.id}", data: { turbo_method: :delete } do %>
  <div class="flex">  
    <svg class="h-6 w-6 sm:h-8 sm:w-8 text-red-500" fill="currentColor" viewBox="0 0 24 24" stroke="currentColor">
    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"/>
    </svg>
    <div class="mt-2 text-[12px] md:text-[15px]">
      <%= recipe.favorites.count %>
    </div>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<% content_for :title, "Editing recipe" %>

<h1 class="text-left text-[16px] sm:text-[20px] font-bold py-2">レシピ編集</h1>

<%= render "form", recipe: @recipe %>

app/views/recipes/favorites.html.erb
<div class="flex justify-between">
  <div class="text-left text-[16px] sm:text-[20px] font-bold py-2">
    お気に入りレシピ一覧
  </div>
  <div class="flex justify-end pt-4 mr-10 text-[12px] sm:text-[20px]">
    <% if user_signed_in? %>
      <%= "こんにちは、#{current_user.name}さん" %>
    <% else %>
      <%= "ようこそ、ゲストさん" %>
    <% end %>
  </div>
</div>

<div class="mb-2 sm:mb-5">
  <p class="text-[12px] sm:text-[18px]">食材で絞り込む</p>
  <p class="text-[10px] sm:text-[16px]">【
    <%= link_to "全て", favorites_recipes_path, class:"hover:underline" %>
    <% @tags.each do |tag| %>
      <span>/</span>
      <%= link_to "#{tag.name}", favorites_recipes_path(tag_id: tag.id), class:"hover:underline" %>
    <% end %>
    】</p>
</div>

<div class="flex">
  <div class="flex justify-center grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-2 sm:gap-8 w-230 mb-3">
    <% @favorite_recipes.each do |recipe| %>
      <%= render recipe %>
    <% end %>
  </div>
</div>

<div class="flex justify-center"><%= paginate @favorite_recipes %></div>

app/views/recipes/show.html.erb
<% assign_meta_tags title: @recipe.title, image: @recipe.image.url(:show_size) %>
<% if @recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<% content_for :title, "Showing recipe" %>

<div class="text-left text-[16px] sm:text-[20px] font-bold py-2">
  レシピ詳細
</div>

<div>
  <div class="flex justify-end mr-5 md:mr-10 md:mb-4">
    <div class="sm:mr-10 pt-3">
      <%= link_to "レシピ検索画面へ", recipes_look_path %>
    </div>
    <% if current_user && current_user.own?(@recipe) %>
      <%= link_to "削除", recipe_path(@recipe), data: { turbo_method: :delete }, class: "rounded-lg bg-red-500 text-white px-4 my-2 mr-2", onclick: "if (!confirm('本当に削除しますか？')) { return false; }" %>
      <%= link_to "編集", edit_recipe_path(@recipe), class: "rounded-lg bg-green-400 text-stone-700 px-4 my-2" %> 
    <% end %>
  </div>

  <div class="md:flex">
    <div class="py-2 md:mr-50 flex justify-center">
      <%= cl_image_tag(@recipe.image.url(:show_size)) %>
    </div>
    <div class="py-2">
      <div class="text-[25px] sm:text-[50px] flex justify-center">
       <%= @recipe.title %>
      </div>
      <div class="flex justify-center">
        <div class="flex rounded-lg w-70 md:w-90 border mt-3 p-1" style="background-color: #F2EDED;">
          <h2 class="text-[12px] sm:text-[15px] ml-2">苦手な食材:</h2> <!-- タイトル -->
          <% @recipe.tags.each do |tag| %>
            <span class="text-[15px] sm:text-[25px] ml-5 sm:ml-10"><%= tag.name %></span>
          <% end %>
        </div>
      </div>
      <div class="flex justify-center mt-3 md:mt-30">
        <div class="flex">
          <div>
            <%= render 'favorite_buttons', recipe:@recipe %>
          </div>
        </div>
        <div class="text-[14px] sm:text-[20px] ml-10 pt-1">
          克服ポイント：<%=@recipe.get_point%>
        </div>
      </div>
    </div>
  </div>
  
  <div class="md:flex mt-5">
    <div class="md:ml-10">
      <div class="text-[16px] sm:text-[20px] mb-3 mt-3 w-[350px]">
       【材料】
      </div>
      <% @recipe.ingredients.each do |ingredient| %>
        <div class="flex justify-between text-[14px] sm:text-[20px] w-[350px] border-b border-gray-400 mb-2">
          <span><%= ingredient.name %></span>
          <span><%= ingredient.quantity %></span>
        </div>
      <% end %>
    </div>
    <div class="md:ml-50">
      <div class="text-[16px] sm:text-[20px] mb-3 mt-3">
       【手順】
      </div>
      <div class="flex grid grid-cols-1 lg:grid-cols-2 xl:grid-cols-3 gap-4 md:gap-7">
        <% @recipe.instructions.each do |instruction| %>
          <div class="flex flex-col text-[14px] sm:text-[20px] mb-5 mr-10">
            <span class="w-10 font-semibold pl-2"><%= instruction.step %></span>
            <span class="mb-2 w-55 rounded-lg px-2"><%= instruction.content %></span>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="rounded-lg w-full md:w-130 border md:ml-150 mt-3 p-2" style="background-color: #F2EDED;"> <!-- 丸みを帯びた四角 -->
    <h2 class="text-[12px] sm:text-[15px]">コツ・工夫点:</h2> <!-- タイトル -->
    <div class="text-[15px] py-2">
      <%= @recipe.trick %>
    </div>
  </div>
</div>
<div class="md:flex md:justify-center mt-10 md:mt-20 pb-10">
  <div>
    <%= render 'comments/form', comment: @comment, recipe: @recipe %>
    <div class="flex flex-col justify-center">
      <div class="text-left text-[14px] sm:text-[20px] font-bold mt-8">
        <p>みんなからのコメント</p>
      </div>
      <div id="table-comment">
        <% @comments.each do |comment| %>
          <%= render comment %>
        <% end %>
      </div>
    </div>
  </div>
</div>