config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
  omniauth_callbacks: "users/omniauth_callbacks" }

  resources :users, only: %i[show edit update] do
    get "point" => "users#total_point"
    post "add_point" => "users#add_point"
    post "subtract_point" => "users#subtract_point"

    resources :rewards, only: %i[new create index] do
    post "update_completed" => "rewards#update_completed"
    end
  end

  get "others/getting_ready" => "others#getting_ready"
  get "others/point_explanation" => "others#point_explanation"

  resources :notifications, only: :index

  get "recipes/look" => "recipes#look"
  get "recipes/ranking" => "recipes#ranking"

  resources :recipes, only: %i[index new create show edit update destroy] do
    collection do
      get :favorites
    end
    get :search, on: :collection
    resources :comments, only: %i[create edit update destroy], shallow: true
  end
  resources :favorites, only: %i[create destroy]

  root "others#top"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [ :google_oauth2 ]
  validates :uid, presence: true, uniqueness: { scope: :provider }, if: -> { uid.present? }

  validates :name, presence: true
  validates :email, presence: true

  has_many :recipes,  dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_recipes, through: :favorites, source: :recipe
  has_many :rewards,  dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :active_notifications, class_name: "Notification", foreign_key: "visitor_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy

  def own?(object)
    id == object&.user_id
  end

  def favorite(recipe)
    favorite_recipes << recipe
  end

  def unfavorite(recipe)
    favorite_recipes.destroy(recipe)
  end

  def favorite?(recipe)
    favorite_recipes.include?(recipe)
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.name = auth.info.name
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    callback_for(:google)
  end

  def callback_for(provider)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in @user
      redirect_to recipes_look_path
      set_flash_message(:notice, :success, kind: provider.to_s.capitalize) if is_navigational_format?
    else
      redirect_to new_user_registration_path
      flash[:alert] = @user.errors.full_messages.to_sentence
    end
  end

  def failure
    redirect_to root_path and return
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(current_user.id)
  end

  def edit
    @user = User.find(current_user.id)
  end

  def update
    @user = User.find(current_user.id)
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "情報の更新に成功しました。" }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def total_point
    @user = User.find(current_user.id)
    @point = @user.point
    @reward = Reward.where(user_id: current_user.id).order(created_at: :desc).limit(1).first
  end

  def add_point
    @user = User.find(current_user.id)
    @user.point += params[:add].to_i
    @point = @user.point
    @reward = Reward.where(user_id: current_user.id).order(created_at: :desc).limit(1).first
    if @user.save
      redirect_to user_point_path(@user)
    else
      render :total_point
      flash.now[:alert] = @user.errors.full_messages
    end
  end

  def subtract_point
    @user = User.find(current_user.id)
    @user.point -= params[:subtract].to_i
    if @user.save
      redirect_to user_point_path(@user)
    else
      render :total_point
      flash.now[:alert] = @user.errors.full_messages.join(", ")
    end
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/edit.html.erb
<h2 class="text-left text-[16px] sm:text-[20px] font-bold py-2">アカウント名変更</h2>
  <%= form_with model: @user do |f| %>
    <div class="field mt-5 text-[14px] sm:text-[20px] md:ml-50">
      <span>アカウント名：</span>
      <div class= "rounded-lg border md:w-140 md:h-12 mt-4 p-2"  style="background-color: #F2EDED;">
        <div class="text-[12px] sm:text-[18px] text-left">
          <%= @user.name %>
        </div>
      </div>
    </div>
    <div class="field mt-8 md:mt-15 text-[14px] sm:text-[20px]">
      <%= f.label :"新しいアカウント名：", class: "md:ml-50" %><br />
      <div class= "flex md:ml-50">
        <%= f.text_field :name, autofocus: true, autocomplete: "name", class: "bg-gray-300 w-full text-[12px] sm:text-[18px] md:w-140 md:h-10 mt-3 p-2" %>
      </div>
    </div>
    <div class="md:ml-115 mt-10 md:mt-20 md:block flex justify-center">
      <%= f.submit "更新", class: "text-[12px] sm:text-[18px] rounded-lg bg-green-300 text-stone-700 px-4 cursor-pointer" %>
    </div>
  <% end %>

app/views/users/show.html.erb
<h2 class="text-left text-[16px] sm:text-[20px] font-bold py-2">アカウント詳細</h2>
<div class="field mt-5 text-[14px] sm:text-[20px] md:ml-50 md:w-200">
  <span>アカウント名：</span>
  <div class="md:flex">
    <div class= "rounded-lg border w-full md:w-140 mt-4 p-2"  style="background-color: #F2EDED;">
      <div class="text-[14px] sm:text-[18px] text-left md:ml-5">
        <%= @user.name %>
      </div>
    </div>
    <div class="flex justify-end ml-3 md:pt-7">
      <%= link_to "編集", edit_user_path %>
    </div>
  </div>
</div>
<div class="field md:mt-15 text-[14px] sm:text-[20px] md:ml-50">
  <span>メールアドレス：</span>
  <div class= "rounded-lg border md:w-140 mt-4 p-2"  style="background-color: #F2EDED;">
    <div class="text-[14px] sm:text-[18px] text-left md:ml-5">
      <%= @user.email %>
    </div>
  </div>
</div>
<div class="text-[12px] sm:text-[20px] md:ml-190 mt-10 md:block flex justify-center md:w-200">
  <%= link_to "レシピ一覧へ", recipes_path, class:"border-b" %>
</div>

app/views/users/total_point.html.erb
<%=javascript_include_tag "add_point" %>
<div class="text-left text-[16px] sm:text-[20px] font-bold py-2">
  克服ポイントカード
</div>
<div class="flex justify-center mb-3">
  <div class="rounded-lg border  md:h-60 p-4 md:p-8 mt-10" style="background-color: #F2EDED;">
    <div class="text-[14px] sm:text-[20px]">
      <%= "#{@user.name} さん" %>
    </div>
    <div class="md:flex ml-10 md:ml-20">
      <p class="text-[20px] sm:text-[32px]">現在</p>
      <p class="text-[40px] sm:text-[56px] font-bold  ml-15 md:mt-5"><%= @user.point %></p>
      <p class="text-[20px] sm:text-[32px] ml-30 md:ml-15 md:mt-15">ポイント</p>
    </div>
  </div>
</div>

<%= form_with(url: user_add_point_path(@user), local: true, html: { id: "add-point-form" }) do |form| %>
  <div class="flex justify-center items-center ml-5 md:ml-40 text-[14px] sm:text-[16px]">
    <%= label_tag :add, "加算するポイント数：" %>
    <%= number_field_tag :add, nil, min: 1, max: 3, placeholder: "0", class: "bg-gray-300 w-6 sm:w-11 pl-1 h-6 sm:h-7" %>
    <p class="ml-2">ポイント</p>
    <%= submit_tag "加算", class: "add_points rounded-lg border px-3.5 py-0.5 ml-3 sm:ml-5 text-[12px] sm:text-[16px]", style: "background-color: #F2EDED;" %>
  </div>
<% end %>
<%= form_with(url: user_subtract_point_path(@user), local: false, html: { id: "#subtract-point-form" }) do |form| %>
  <div class="flex justify-center items-center mt-1 ml-5 md:ml-40 text-[14px] sm:text-[16px]">
    <%= label_tag :subtract, "減算するポイント数：" %>
    <%= number_field_tag :subtract, nil, min: 1, max: 3, placeholder: "0", class: "bg-gray-300 w-6 sm:w-11 pl-1 h-6 sm:h-7" %>
    <p class="ml-2">ポイント</p>
    <%= submit_tag "減算", class: "rounded-lg border px-3.5 py-0.5 ml-3 sm:ml-5 text-[12px] sm:text-[16px]", style: "background-color: #F2EDED;" %>
  </div>
<% end %>

<p class="text-center mt-4 text-red-700 text-[14px] sm:text-[16px]">※ポイントは1~3の数値を入力してください</p>

<div class="flex justify-center mt-7 md:mt-10">
  <div class="rounded-lg border w-full md:w-150 border-neutral-400 bg-neutral-100/70 p-2">
    <div class="flex items-end">
      <span class="text-[14px] sm:text-[20px]">目標： </span>
      <span class="text-[18px] sm:text-[24px]"><%= "#{@reward.required_points}" %></span>
      <span class="text-[14px] sm:text-[20px] ml-2"> ポイント</span>
    </div>
    <div class="mt-3 md:mt-5 pb-2">
      <p class="text-[14px] sm:text-[20px]">ごほうび：</p>
      <div class="w-full md:w-150">
        <span class="text-[18px] sm:text-[24px]"><%= "#{@reward.content}" %></span>
      </div>
    </div>
  </div>
</div>

<div class="flex justify-center">
  <div class="flex justify-between w-150  mt-10 pb-20 text-[14px] sm:text-[20px]">
    <%= link_to "今までのこほうび", user_rewards_path(current_user.id) %>
    <%= link_to "克服ポイントとは？", others_point_explanation_path %>
  </div>
</div>

<div id="goalAchievedModal" class="modal hidden fixed inset-0 flex items-center justify-center bg-gray-300/50">
  <div class="modal-content bg-yellow-100 border-3 border-red-500 p-6 rounded-lg shadow-lg text-center max-w-md w-full">
    <span class="close-button cursor-pointer text-2xl absolute top-4 right-4">&times;</span>
    <h2 class="text-2xl font-bold">おめでとうございます！</h2>
    <p>目標ポイントを達成しました。</p>
    <p>ごほうびをあげてください。</p>
    <p><%= "★#{@reward.content}★" %></p>
  </div>
</div>

<div id="reward-data" 
     data-required-points="<%= @reward.required_points %>" 
     data-user-points="<%= @point %>" 
     data-user-id="<%= current_user.id %>" 
     data-reward-id="<%= @reward.id %>">
</div>