config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
  omniauth_callbacks: "users/omniauth_callbacks" }

  resources :users, only: %i[show edit update] do
    get "point" => "users#total_point"
    post "add_point" => "users#add_point"
    post "subtract_point" => "users#subtract_point"

    resources :rewards, only: %i[new create index] do
    post "update_completed" => "rewards#update_completed"
    end
  end

  get "others/getting_ready" => "others#getting_ready"
  get "others/point_explanation" => "others#point_explanation"

  resources :notifications, only: :index

  get "recipes/look" => "recipes#look"
  get "recipes/ranking" => "recipes#ranking"

  resources :recipes, only: %i[index new create show edit update destroy] do
    collection do
      get :favorites
    end
    get :search, on: :collection
    resources :comments, only: %i[create edit update destroy], shallow: true
  end
  resources :favorites, only: %i[create destroy]

  root "others#top"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/views/shared/_before_login_header.html.erb
<header>
  <nav class="bg-green-300">
    <div class="flex justify-between">
      <div class="text-[16px] font-normal text-left ml-2 md:ml-10 pt-4">
        さぁ、まずはひとくち
      </div>
      <dev class="mr-5 sm:mr-10 sm:mb-2 pt-3">
      <%= link_to 'ログイン', new_user_session_path, class: 'text-[12px] sm:text-[20px] login-button rounded-lg bg-gray-200 p-1' %>
      </div>
    </div>
    <hr class="border-t-2 border-white mt-2" style="border-color: white;" /> <!-- マージンを調整 -->
    <div class="block md:hidden">
      <%= render 'shared/before_login_header_humberger' %>
    </div>
    <div class="hidden md:block">
      <%= render 'shared/before_login_header_icon' %>
    </div>
  </nav>
</header>

<script>
function toggleMenu(button) {
    const menu = document.getElementById('humbergerMenu');
    menu.classList.toggle('hidden');

    const menuIcon = button.querySelector('svg');
    if (menu.classList.contains('hidden')) {
      menuIcon.innerHTML = '<path d="M24 6h-24v-4h24v4zm0 4h-24v4h24v-4zm0 8h-24v4h24v-4z"/>';
    } else {
      menuIcon.innerHTML = '<path v-show="isOpen" d="M24 20.188l-8.315-8.209 8.2-8.282-3.697-3.697-8.212 8.318-8.31-8.203-3.666 3.666 8.321 8.24-8.206 8.313 3.666 3.666 8.237-8.318 8.285 8.203z"/>';
    }
  }
</script>

app/views/shared/_before_login_header_humberger.html.erb
<div class="flex justify-between">
  <div class="text-left ml-2 md:ml-10 pt-1 sm:pt-4">
    <%= link_to "Kutemy", root_path, class: "font-bold text-3xl sm:text-5xl", data: { turbo: false } %>
  </div>
  <div class="humberger flex justify-end mr-10 sm:py-1">
    <button class="humberger_icon cursor-pointer items-center space-x-8 h-[50px] sm:h-[80px]" onclick="toggleMenu(this)">
      <svg class="w-4 h-4 sm:h-6 sm:w-6 fill-current" viewBox="0 0 24 24" id="menuIcon">
      <path d="M24 6h-24v-4h24v4zm0 4h-24v4h24v-4zm0 8h-24v4h24v-4z"/>
      </svg>                  
    </button>
  </div>
</div>
<div id="humbergerMenu" class="text-[14px] sm:text-[18px] humberger_menu hidden mx-10 mt-1 py-2 md:py-4">
  <ul>
    <%= link_to "レシピを探す", recipes_look_path, class: "border-b block px-4 hover:bg-green-400" %>
    <%= link_to "投稿する",new_recipe_path, class: "border-b block px-4 hover:bg-green-400", onclick: "alert('ログインしてください。'); window.location='#{new_user_session_path}'" %>
    <%= link_to "ランキング",recipes_ranking_path, class: "block px-4 hover:bg-green-400", onclick: "alert('ログインしてください。'); window.location='#{new_user_session_path}'" %>
  </ul>
</div>

app/views/shared/_before_login_header_icon.html.erb
<div class="flex justify-between">
  <div class="text-left ml-2 md:ml-10 pt-1 sm:pt-4">
    <%= link_to "Kutemy", root_path, class: "font-bold text-3xl sm:text-5xl", data: { turbo: false } %>
  </div>
  <div class="flex justify-end font-bold items-center space-x-8 h-[50px] sm:h-[80px] mr-10">
    <%= link_to(recipes_look_path)  do %>
      <div class="flex flex-col items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24">
          <path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m15 15l6 6m-11-4a7 7 0 1 1 0-14a7 7 0 0 1 0 14"/>
        </svg>
        <span class="text-[10px]">レシピを探す</span>
      </div>
    <% end %>
    <%= link_to do %>
      <div class="flex flex-col items-center" onclick="alert('ログインしてください。'); window.location='<%= new_user_session_path %>';">
        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 20 20">
          <path fill="currentColor" fill-rule="evenodd" d="m5.433 13.916l1.262-3.154a4 4 0 0 1 .885-1.343L14.5 2.5a2.121 2.121 0 1 1 3 3l-6.92 6.919c-.383.383-.84.684-1.343.885l-3.154 1.262a.5.5 0 0 1-.65-.65ZM2.5 5.75c0-.69.56-1.25 1.25-1.25H10A.75.75 0 0 0 10 3H3.75A2.75 2.75 0 0 0 1 5.75v10.5A2.75 2.75 0 0 0 3.75 19h10.5A2.75 2.75 0 0 0 17 16.25V10a.75.75 0 0 0-1.5 0v6.25c0 .69-.56 1.25-1.25 1.25H3.75c-.69 0-1.25-.56-1.25-1.25V5.75Z" clip-rule="evenodd"/>
        </svg>
        <span class="text-[10px]">投稿する</span>
      </div>
    <% end %>
    <%= link_to do %>
      <div class="flex flex-col items-center" onclick="alert('ログインしてください。'); window.location='<%= new_user_session_path %>';">
        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 256 256">
          <path fill="currentColor" d="M240 200h-8v-56a16 16 0 0 0-16-16h-40V56a16 16 0 0 0-16-16H96a16 16 0 0 0-16 16v32H40a16 16 0 0 0-16 16v96h-8a8 8 0 0 0 0 16h224a8 8 0 0 0 0-16m-160 0H40v-96h40Zm60-64a8 8 0 0 1-16 0v-28.9l-1.47.49a8 8 0 0 1-5.06-15.18l12-4A8 8 0 0 1 140 96Zm76 64h-40v-56h40Z"/>
        </svg>
        <span class="text-[10px]">ランキング</span>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer>
  <nav class="bg-green-300 pb-3 text-[12px] sm:text-[16px]">
    <div class="ml-2 md:ml-10 pt-2">
      <p class="font-semibold">○ご利用案内</p>
      <div class="ml-5 my-3">
        <ul class="list-disc list-outside">
          <li><%= link_to "利用規約", page_path('terms') %></li>
          <li><%= link_to "プライバシーポリシー", page_path('policy') %></li>
        </ul>
      </div>
    </div>
  </nav>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class="bg-green-300">
    <div class="flex justify-between">
      <div class="text-[12px] sm:text-[16px] font-normal text-left ml-2 md:ml-10 pt-4">
        さぁ、まずはひとくち
      </div>
      <div class="flex justify-end font-bold items-center space-x-2 sm:space-x-8 mr-5 sm:mr-20"> 
        <% if unchecked_notifications.any? %>
          <%= link_to(notifications_path)  do %>
            <div class="flex flex-col items-center">
              <div style="position: relative; display: inline-block;">
              <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 sm:w-8 sm:h-8" viewBox="0 0 24 24">
                <path fill="currentColor" d="M12 22a2.98 2.98 0 0 0 2.818-2H9.182A2.98 2.98 0 0 0 12 22m7-7.414V10c0-3.217-2.185-5.927-5.145-6.742C13.562 2.52 12.846 2 12 2s-1.562.52-1.855 1.258C7.185 4.074 5 6.783 5 10v4.586l-1.707 1.707A1 1 0 0 0 3 17v1a1 1 0 0 0 1 1h16a1 1 0 0 0 1-1v-1a1 1 0 0 0-.293-.707z"/>
                </svg>
                <svg class="h-3 w-3 sm:h-4 sm:w-4 text-red-500" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round" style="position: absolute; top: 0; left: 16;">
                <path stroke="none" d="M0 0h24v24H0z"/>  
                <circle cx="12" cy="12" r="9" fill="currentColor" />
                </svg>
              </div>
            </div>
          <% end %>
        <% else %>
          <%= link_to(notifications_path)  do %>
            <div class="flex flex-col items-center">
              <div style="position: relative; display: inline-block;">
              <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 sm:w-8 sm:h-8" viewBox="0 0 24 24">
                <path fill="currentColor" d="M12 22a2.98 2.98 0 0 0 2.818-2H9.182A2.98 2.98 0 0 0 12 22m7-7.414V10c0-3.217-2.185-5.927-5.145-6.742C13.562 2.52 12.846 2 12 2s-1.562.52-1.855 1.258C7.185 4.074 5 6.783 5 10v4.586l-1.707 1.707A1 1 0 0 0 3 17v1a1 1 0 0 0 1 1h16a1 1 0 0 0 1-1v-1a1 1 0 0 0-.293-.707z"/>
                </svg>
              </div>
            </div>
          <% end %>
        <% end %>
        <div class="relative inline-block flex flex-col items-center">
          <div class="user_icon cursor-pointer">
          <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6 sm:w-9 sm:h-9" viewBox="0 0 24 24">
            <path fill="currentColor" d="M12 12q-1.65 0-2.825-1.175T8 8t1.175-2.825T12 4t2.825 1.175T16 8t-1.175 2.825T12 12m-8 8v-2.8q0-.85.438-1.562T5.6 14.55q1.55-.775 3.15-1.162T12 13t3.25.388t3.15 1.162q.725.375 1.163 1.088T20 17.2V20z"/>
            </svg>
          </div>
          <div class="user_menu absolute hidden text-[12px] sm:text-[18px] bg-white border border-gray-300 w-30 sm:w-40 shadow-lg right-5 top-5">
            <ul>
              <%= link_to "アカウント詳細", user_path(current_user.id), class: "block px-2 md:px-4 md:py-2 hover:bg-gray-100" %>
              <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete }, class: "block px-2 md:px-4 md:py-2 hover:bg-gray-100" %>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <hr class="border-t-2 border-white mt-2" style="border-color: white;" /> <!-- マージンを調整 -->
    <div class="block md:hidden">
      <%= render 'shared/header_humberger' %>
    </div>
    <div class="hidden md:block">
      <%= render 'shared/header_icon' %>
    </div>
  </nav>
</header>


<script>
document.addEventListener('turbo:load', () => {
const user_icon = document.querySelector('.user_icon');
const user_menu = document.querySelector('.user_menu');

user_icon.addEventListener('mouseenter', () => {
  user_menu.classList.remove('hidden'); // メニューを表示
});

user_icon.addEventListener('mouseleave', () => {
  user_menu.classList.add('hidden'); // メニューを非表示
});

user_menu.addEventListener('mouseenter', () => {
  user_menu.classList.remove('hidden'); // メニューを表示
});

user_menu.addEventListener('mouseleave', () => {
  user_menu.classList.add('hidden'); // メニューを非表示
});
});

function toggleMenu(button) {
    const menu = document.getElementById('humbergerMenu');
    menu.classList.toggle('hidden');

    const menuIcon = button.querySelector('svg');
    if (menu.classList.contains('hidden')) {
      menuIcon.innerHTML = '<path d="M24 6h-24v-4h24v4zm0 4h-24v4h24v-4zm0 8h-24v4h24v-4z"/>';
    } else {
      menuIcon.innerHTML = '<path v-show="isOpen" d="M24 20.188l-8.315-8.209 8.2-8.282-3.697-3.697-8.212 8.318-8.31-8.203-3.666 3.666 8.321 8.24-8.206 8.313 3.666 3.666 8.237-8.318 8.285 8.203z"/>';
    }
  }
</script>

app/views/shared/_header_humberger.html.erb
<div class="flex justify-between">
<div class="text-left ml-2 md:ml-10 pt-1 sm:pt-4">
  <%= link_to "Kutemy", root_path, class: "font-bold text-3xl sm:text-5xl", data: { turbo: false } %>
</div>
  <div class="humberger flex justify-end mr-10">
    <button class="humberger_icon cursor-pointer items-center space-x-8 h-[50px] sm:h-[80px]" onclick="toggleMenu(this)">
      <svg class="w-4 h-4 sm:h-6 sm:w-6 fill-current" viewBox="0 0 24 24" id="menuIcon">
      <path d="M24 6h-24v-4h24v4zm0 4h-24v4h24v-4zm0 8h-24v4h24v-4z"/>
      </svg>                  
    </button>
  </div>
</div>
<div id="humbergerMenu" class="text-[14px] sm:text-[18px] humberger_menu hidden mx-10 mt-1 py-2 md:py-4">
  <ul>
    <%= link_to "レシピを探す",recipes_look_path, class: "border-b block px-4 hover:bg-green-400" %>
    <%= link_to "いいねレシピ",favorites_recipes_path, class: "border-b block px-4 hover:bg-green-400" %>
    <%= link_to "投稿する",new_recipe_path, class: "border-b block px-4 hover:bg-green-400" %>
    <% if current_user.rewards.where(completed: false).present? %>
      <%= link_to "克服ポイント",user_point_path(current_user.id), class: "border-b block px-4 hover:bg-green-400" %>
    <% else %>
      <%= link_to "克服ポイント",new_user_reward_path(current_user.id), class: "border-b block px-4 hover:bbg-green-400" %>
    <% end %>
    <%= link_to "ランキング",recipes_ranking_path, class: "block px-4 hover:bg-green-400" %>
  </ul>
</div>

app/views/shared/_header_icon.html.erb
<div class="flex justify-between">
  <div class="text-left ml-2 md:ml-10 pt-1 sm:pt-4">
    <%= link_to "Kutemy", root_path, class: "font-bold text-3xl sm:text-5xl", data: { turbo: false } %>
  </div>
  <div class="header_icon">
    <div class="flex justify-end font-bold items-center space-x-8 h-[50px] sm:h-[80px] mr-10">
      <%= link_to(recipes_look_path)  do %>
        <div class="flex flex-col items-center">
          <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24">
            <path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m15 15l6 6m-11-4a7 7 0 1 1 0-14a7 7 0 0 1 0 14"/>
          </svg>
          <span class="text-[10px]">レシピを探す</span>
        </div>
      <% end %>
      <%= link_to(favorites_recipes_path)  do %>
        <div class="flex flex-col items-center">
          <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 20 20">
            <path fill="currentColor" fill-rule="evenodd" d="M3.172 5.172a4 4 0 0 1 5.656 0L10 6.343l1.172-1.171a4 4 0 1 1 5.656 5.656L10 17.657l-6.828-6.829a4 4 0 0 1 0-5.656" clip-rule="evenodd"/>
          </svg>
          <span class="text-[10px]">いいねレシピ</span>
        </div>
      <% end %>
      <%= link_to(new_recipe_path)  do %>
        <div class="post flex flex-col items-center">
          <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 20 20">
            <path fill="currentColor" fill-rule="evenodd" d="m5.433 13.916l1.262-3.154a4 4 0 0 1 .885-1.343L14.5 2.5a2.121 2.121 0 1 1 3 3l-6.92 6.919c-.383.383-.84.684-1.343.885l-3.154 1.262a.5.5 0 0 1-.65-.65ZM2.5 5.75c0-.69.56-1.25 1.25-1.25H10A.75.75 0 0 0 10 3H3.75A2.75 2.75 0 0 0 1 5.75v10.5A2.75 2.75 0 0 0 3.75 19h10.5A2.75 2.75 0 0 0 17 16.25V10a.75.75 0 0 0-1.5 0v6.25c0 .69-.56 1.25-1.25 1.25H3.75c-.69 0-1.25-.56-1.25-1.25V5.75Z" clip-rule="evenodd"/>
          </svg>
          <span class="text-[10px]">投稿する</span>
        </div>
      <% end %>
      <% if current_user.rewards.where(completed: false).present? %>
        <%= link_to(user_point_path(current_user.id))  do %>
          <div class="card flex flex-col items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 20 20">
              <path fill="currentColor" d="M4 4a2 2 0 0 0-2 2v1h16V6a2 2 0 0 0-2-2z"/>
              <path fill="currentColor" fill-rule="evenodd" d="M18 9H2v5a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2zM4 13a1 1 0 0 1 1-1h1a1 1 0 1 1 0 2H5a1 1 0 0 1-1-1m5-1a1 1 0 1 0 0 2h1a1 1 0 1 0 0-2z" clip-rule="evenodd"/></g>
            </svg>
            <span class="text-[10px]">克服ポイント</span>
          </div>
        <% end %>
      <% else %>
        <%= link_to(new_user_reward_path(current_user.id))  do %>
          <div class="flex flex-col items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 20 20">
              <path fill="currentColor" d="M4 4a2 2 0 0 0-2 2v1h16V6a2 2 0 0 0-2-2z"/>
              <path fill="currentColor" fill-rule="evenodd" d="M18 9H2v5a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2zM4 13a1 1 0 0 1 1-1h1a1 1 0 1 1 0 2H5a1 1 0 0 1-1-1m5-1a1 1 0 1 0 0 2h1a1 1 0 1 0 0-2z" clip-rule="evenodd"/></g>
            </svg>
            <span class="text-[10px]">克服ポイント</span>
          </div>
        <% end %>
      <% end %>
      <%= link_to(recipes_ranking_path) do %>
        <div class="flex flex-col items-center">
          <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 256 256">
            <path fill="currentColor" d="M240 200h-8v-56a16 16 0 0 0-16-16h-40V56a16 16 0 0 0-16-16H96a16 16 0 0 0-16 16v32H40a16 16 0 0 0-16 16v96h-8a8 8 0 0 0 0 16h224a8 8 0 0 0 0-16m-160 0H40v-96h40Zm60-64a8 8 0 0 1-16 0v-28.9l-1.47.49a8 8 0 0 1-5.06-15.18l12-4A8 8 0 0 1 140 96Zm76 64h-40v-56h40Z"/>
          </svg>
          <span class="text-[10px]">ランキング</span>
        </div>
      <% end %>
    </div>
  </div>
</div>